config/routes.rb
Rails.application.routes.draw do

  get 'vibe_codes/test'

  get 'vibe_codes/new'

  get 'vibe_codes/index'

resources :users do
  resources :wallet do
    resources :vibe_codes
  end
  resources :skills
  resources :posts
end
  patch 'user/update', to: 'users#update'
  get 'user/show', to: 'users#show', as: 'show_profile'
  get 'user/:user_id/post/:post_id', to: 'posts#show', as: 'show_post'

  get 'user/:id', to: 'users#show_other', as: 'show_other_profile'

  get 'skills/all/show', to: 'skills#index', as: 'skills_index'

  post 'vibes/redeem', to: 'vibe_codes#redeem'
  root 'static_pages#home'

  get 'user/edit', to: 'users#edit', as: 'edit_profile'

  match 'auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
  match 'auth/failure', to: redirect('/'), via: [:get, :post]
  match 'signout', to: 'sessions#destroy', as: 'signout', via: [:get, :post]

end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id         :integer          not null, primary key
#  title      :string
#  body       :text
#  expiration :date
#  user_id    :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Post < ActiveRecord::Base
  belongs_to :user, dependent: :destroy
end

app/models/skill.rb
# == Schema Information
#
# Table name: skills
#
#  id         :integer          not null, primary key
#  maincat    :string
#  subcat     :string
#  subsubcat  :string
#  experience :integer
#  need       :boolean
#  offer      :boolean
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  image_url  :string
#  user_id    :integer
#

class Skill < ActiveRecord::Base
  belongs_to :user, dependent: :destroy

  MAINCATS = [ 'automotive repair',
  'computer',
  'creative / arts, performance, dance, photography',
  'creative / marketing, crafts, design, branding',
  'childcare',
  'classes & education',
  'bicycle repair',
  'event planning & help',
  'farm & garden skills',
  'financial skills',
  'food & household',
  'hair / beauty',
  'manual labor / moving',
  'legal skills',
  'life coaching',
  'professional development',
  'pet care',
  'real estate, business, negotiation',
  'skilled trade',
  'therapy (physical and mental)',
  'travel, vacation & tours',
  'writing, editing & translation',
  'other'
  ]

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id               :integer          not null, primary key
#  location_long    :float
#  location_lat     :float
#  username         :string
#  age              :integer
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#  provider         :string
#  uid              :string
#  name             :string
#  oauth_token      :string
#  oauth_expires_at :datetime
#  email            :string
#  image_url        :string
#  availability     :text             default([]), is an Array
#  zipcode          :string
#

require 'zipcode_finder'

class User < ActiveRecord::Base
  has_many :skills, dependent: :destroy
  has_many :posts, dependent: :destroy
  has_one :wallet

  # has_many :generated_coupons, class_name: "Coupon", foreign_key: :generated_by_user_id
  # has_many :cashed_coupons, class_name: "Coupon", foreign_key: :cashed_by_user_id

  before_save 'set_long_lat'
  after_create 'create_wallet'


  def self.from_omniauth(auth)
    Rails.logger.debug auth
    User.where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.name = auth.info.name
      user.email = auth.info.email
      user.image_url = auth.info.image
      user.oauth_token = auth.credentials.token
      user.oauth_expires_at = Time.at(auth.credentials.expires_at)
      user.save!
    end
  end

private

  def create_wallet
    Wallet.create(user_id: id) if wallet.nil?
  end

  def set_long_lat
    api = ZipcodeLocation.new(zipcode)
    self.location_long, self.location_lat = api.get_long_lat
  end
end

app/models/wallet.rb
# == Schema Information
#
# Table name: wallets
#
#  id         :integer          not null, primary key
#  balance    :integer
#  credit     :integer
#  debit      :integer
#  last_used  :date
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :integer
#

class Wallet < ActiveRecord::Base
  # after_commit 'balance_calculator'

  belongs_to :user, dependent: :destroy
  has_many :generated_coupons, :foreign_key => "giver_wallet_id", :class_name => "VibeCode"
  has_many :received_coupons, :foreign_key => "receiver_wallet_id", :class_name => "VibeCode"

  def balance_calculator
    self.balance = wallet.received_coupons.credit_equiv
  end


end

app/controllers/posts_controller.rb
class PostsController < ApplicationController


  def create
    @post = current_user.posts.create(post_params)
    redirect_to show_profile_path
  end

  def new
    @post = Post.new
  end

  def show
    @users = User.all
    @user = User.find(params[:user_id])
    @post = get_post
  end

  private
    def post_params
      params.require(:post).permit(:title, :body, :expiration)
    end

    def get_post
      Post.find(params[:post_id])
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index

  end

  def show_other
    @users = User.all
    @user = User.find(params[:id])
  end


  def new
  end


  def update
    Rails.logger.debug
    if current_user.update!(user_params)
      redirect_to show_profile_path
    else
      render 'edit'
    end

  end




  def show
    @skills = current_user.skills
    @posts = current_user.posts
  end


  private
    def user_params
      params.require(:user).permit(:name, :zipcode, :location_long, :username, {:availability => []}, :email, :age, :image_url)
    end

    def get_skill
      Skill.find(params[:id])
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta content="width=device-width, initial-scale=1" name="viewport" />
  <title>Nortia</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>


  <nav id="mainNav" class="navbar navbar-default navbar-fixed-top">
      <div class="container-fluid">
          <!-- Brand and toggle get grouped for better mobile display -->
          <div class="navbar-header">
              <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                  <span class="sr-only">Toggle navigation</span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
              </button>
              <a class="navbar-brand page-scroll" href="/"><div class="logo-spot"></div></a>
          </div>

          <!-- Collect the nav links, forms, and other content for toggling -->
          <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

              <ul class="nav navbar-nav navbar-right">
                <li>
                    <a class="page-scroll" href="/">Home</a>
                </li>

                <li>
                    <a class="page-scroll" href="/skills/all/show">Listings</a>
                </li>
                <li>
                    <% if current_user %>
                    <a class="page-scroll" href="/user/show">My Dashboard</a>
                    <% end %>
                </li>
                <li>
                  <%= link_to 'About', page_path('about') %>
                </li>
                <li><% if current_user %>
                <%= link_to "Sign out", signout_path, id: "sign_out" %>
                <% end %>
              </li>
                <li><% if current_user %> Hi <%= current_user.name %>!</li>
              <% else %>
              <li>
                <%= link_to "Sign in with Facebook", "/auth/facebook", id: "sign_in" %>
              </li>
              <% end %>

            </ul>


          </div>
          <!-- /.navbar-collapse -->
      </div>
      <!-- /.container-fluid -->
  </nav>

<%= yield %>

</body>
</html>

app/views/pages/about.html.erb
<section id = "page-top">
  <div class = "container-fluid col-xs-12 col-lg-8">

    <div class = "panel-heading"><h3>ABOUT</h3></div>

    </div>
  </div>
</section>

app/views/posts/index.html.erb
<li>
  <li><h4><%=post.title%></h4></li>
  <%=post.id%>
</li>

app/views/posts/new.html.erb
<section id = "page-top">
  <div class = "container-fluid col-xs-12 col-lg-8">

  <div class = "panel-heading"><h2>Add a post:</h2></div>
      <%= simple_form_for([current_user, current_user.posts.build]) do |f| %>
        <p>
          <%=current_user.id%>
          <%= f.input :title, label: 'post title', placeholder: 'art director advice wanted for disney short', as: :string %>
        </p>
        <p>
          <%= f.input :body, label: 'more details', as: :text %>
        </p>
        <p>
          <%= f.input :expiration, label: 'need by date', as: :date %>
        </p>
        <p>
          <%= f.button :submit %>
        </p>
      <% end %>
  </div>
</section>

app/views/posts/show.html.erb
<section id = "page-top">
    <div class = "container-fluid col-xs-12 col-lg-8">

    <div class= "row-fluid center-block">
        <h2>Post</h2>
    </div>
    <li><h4>Title: <%=@post.title%></h4></li>
    <li><h4>More Info: <%=@post.body%></h4></li>
    <li><h4>Expires: <%=@post.expiration%></h4></li>
    <li><h4>Contact: <%=@user.email%></h4></li>


    <%=@post.id%>
  </div>
</section>

app/views/skills/index.html.erb
<script type="text/javascript">


</script>

<section id = "page-top">
  <div class="jumbotron">
  <h1>Hello, world!</h1>
  <p>Hello, world!</p>
</div>
</section>
<div class = "container-fluid">
    <div class="row row-layouts">
      <div class="col-md-4 left-skills">
        <h2>Skills</h2>
        <p>
          <p><a class="btn btn-primary btn-sm" onclick="toggle_visibility('listbyskill');" href="#" role="button">Browse by Skills</a></p>
          <p><a class="btn btn-primary btn-sm" href="#" onclick="hide_it('listbyposting');" role="button">Browse by Posting</a></p>
          <div class="col-md-8 searchbar">
            <div class="input-group">
               <input type="text" class="form-control" placeholder="Search for...">
               <span class="input-group-btn">
                 <button class="btn btn-primary" type="button">Go!</button>
               </span>
            </div><!-- /input-group -->
          </div>
        </p>
      </div>

      <div class = "col-md-8 right-layout">
        <!-- <h1>Skills#index</h1>
        <p>Find me in app/views/skills/index.html.erb</p>
        <br> -->
        <div id = "listbyposting" style='display:none'>
          <div class="row row-layouts">
              POSTINGSSSS
          </div>
        </div>

        <div id = "listbyskill" style='display:none'>
          <div class="row row-layouts">
              <%@skills_hash.each do |skill, users| %>
                  <div class="col-md-4 box-inside">
                      <a href="#" onclick="toggle_visibility('<%=skill%>');">
                      <h4><%=skill%></h4>
                      </a>
                  </div>

                  <div id= '<%=skill%>' class='popout-top' style='display:none'>
                    <%users.compact.each do |user|%>
                      <li><%=link_to "#{user.name}", show_other_profile_path(user.id)%></li>
                    <% end %>
                    <li>Add yourself to this list</li>
                  </div>

              <% end %>
          </div>
        </div>






        <!-- <a href="javascript:ShowContent('uniquename')">
        Click to show.
        </a> -->

        <!-- <%@skills_hash.each do |skill, users| %>
        <div class="col-md-4">
            <h4><%=skill%></h4>
            <ul>
            <%users.compact.each do |user|%>
              <li><%=link_to "#{user.name}", show_other_profile_path(user.id)%></li>
            <% end %>
          </ul>
        <% end %>
        </div> -->


      </div>
  </div>
</div>

app/views/users/show.html.erb
<section id = "page-top">

  <div class="jumbotron">
      <h2>Hey <%=current_user.name%>!</h2>
      <h2>You're lookin' good today!</h2>
  </div>
  <!-- <p>Find me in app/views/users/show.html.erb</p> -->

</section>
<div class = "container-fluid">
  <div class="row row-layouts">
    <div class="col-md-4 left-dash span3 centering text-center">
      <%=image_tag(current_user.image_url, class: 'img-circle img-responsive', id: 'profile-pic')  %>
      <h4><%=current_user.name%></h4>
      <li><em>Name</em> <%=current_user.name%></li>
      <li><em>Username</em>  <%=current_user.username%></li>

      <li><em>Email</em>  <%=current_user.email%></li>
      <li><em>Location</em>  <%=current_user.zipcode%></li>
      <li><em>Age</em>  <%=current_user.age%></li>
      <li><em>Longitude</em>  <%=current_user.location_long%></li>
      <li><em>Latitude</em>  <%=current_user.location_lat%></li>
    </div>
<!-- WALLET -->
      <div class = "col-md-8 right-layout-dash">
          <h2>Wallet:</h2>
          <h4>Cha-ching! 💸 </h4>
          <%=current_user.wallet%>
          <h4>You've got <%=current_user.wallet.balance%> credits</h4>
          <%= link_to 'Generate a credit code', vibe_codes_new_path, class: "btn btn-sm btn-default"%>
          <br>
          <%= link_to 'Redeem a credit code', vibe_codes_test_path, class: "btn btn-sm btn-default"%>

<!-- availability -->
          <h2>General Availability</h2>
            <li><%current_user.availability.each do |day|%></li>
          <li><%=day%></li>
          <%end%>
          <%= link_to 'Edit my profile & Availability', edit_user_path(current_user), class: "btn btn-md btn-default"%>

<!-- SKILLS -->
          <h2>Skills I have</h2>
          <%@skills.each do |skill|%>
            <li><%=skill.maincat%> <%=link_to 'Edit skill', edit_user_skill_path(current_user, skill), class: "btn btn-sm btn-default"%>
          <%end%></li>
          <br>
          <%= link_to 'Add new skill', new_user_skill_path(current_user), class: "btn btn-sm btn-default"%>


<!-- POSTS -->
          <h2>My posts:</h2>
          <%= link_to 'Add new post', new_user_post_path(current_user), class: "btn btn-sm btn-default"%>

          <% current_user.posts.each do |post| %>
            <p>
              <strong>title:</strong><br>
              <%= post.title %><br>
              <strong>body:</strong><br>
              <%= post.body %><br>
              <strong>need by date:</strong><br>
              <%= post.expiration %><br>
            </p>
          <% end %>

      </div>

    </div>

  </div>
</div>










  <!-- <div class="span3 centering text-center">
      <div class= "row-fluid center-block"> -->
      <!-- </div> -->

      <!-- <div class="row-fluid center-block"> -->
      <!-- </div> -->

app/views/users/show_other.html.erb
<section id = "page-top">
<!-- <h1>Users#showother</h1>
<p>Find me in app/views/users/show_other.html.erb</p> -->
<div class="container-fluid col-md-8 col-md-offset-2">
    <div class= "row-fluid center-block">

      <div class="span1 centering text-center">
          <h2><%=@user.name%></h2>

      <!-- <p>Find me in app/views/users/show.html.erb</p> -->
      <div class="span3 centering text-center">
          <div class="row-fluid">
            <%=image_tag(@user.image_url, class: 'img-circle img-responsive', id: 'profile-pic')  %>

              <div class="row-fluid">
                <ul>
              <li><em>Name</em> <%=@user.name%></li>
              <li><em>Username</em>  <%=@user.username%></li>

              <% if session[:user_id].nil? %>
              <li>Please sign up to see this person's email, location and skills!</li>

              <% else %>
                <li><em>Email</em>  <%=@user.email%></li>
                <li><em>Location</em> <%=@user.zipcode%></li>
                <li><em>Age</em>  <%=@user.age%></li>
                <li><em>Longitude</em>  <%=@user.location_long%></li>
                <li><em>Latitude</em>  <%=@user.location_lat%></li>
                </ul>
                </div>

                <h2>General Availability</h2>
                <li><%@user.availability.each do |day|%></li>
                <li><%=day%></li>
                <%end%>

              <%end%>
          </div>
      </div>
  </div>


    <div class="span3 centering text-center">
        <div class= "row-fluid center-block">
            <h2>Skills she has</h2>
        </div>

        <div class="row-fluid center-block">
          <ul>
          <%@user.skills.each do |skill|%>
            <li>
              <li><h4><%=skill.maincat%></h4></li>
              <li>She says: "<%=skill.subcat%>"</li>
            </li>
          <%end%>
          </ul>
          <br>
        </div>
    </div>


    <div class="span3 centering text-center">
        <div class= "row-fluid center-block">
            <h2>Recent posts</h2>
        </div>

        <div class="row-fluid center-block">
          <ul>
          <%@user.posts.each do |post|%>
              <li><h4><%=post.title%></h4>
              <%= link_to 'See More', show_post_path(@user.id, post.id), class: "btn btn-sm btn-primary"%>
            </li>
            <br>
          <%end%>
          </ul>
          <br>
        </div>
    </div>


  </div>
</div>

</section>